### ISSUE TITLE
Replace control.sh with more robust controller

### ISSUE THREAD

**Issue by sanmai-NL** [clarin-eric/pyFF_config#2]
A number of aspects of batch job programming are hard to manage with shell programming:
- Making sure exceptions are propagated out of the shell script (exit status, etc.).
- Complex conditional behavior.
- Quoting and escaping strings.
- Fault tolerance, esp. [restartability](https://en.wikipedia.org/wiki/Microreboot)

However, this project relies on a shell script, `control.sh`.
An alternative language should be used to reimplement the functionality of `control.sh`.

In my view the following requirements are most important:
1. No reliance on a runtime context (versions, peculiars of specific distributions, etc.);
2. Minimal distribution size;
3. Secure;
4. Maintainable.

The first two criteria would prohibit e.g. [Python](https://www.python.org), .NET, Java and other managed languages. C, C++ etc. would not go well with criteria 3 and 4. To the contrary, Rust and Go would be good candidates, esp. Rust as it has a focus on systems programming. However, current and future software developers must care for whatever the solution is, for it to be truly maintainable.

`control.sh` in turn depends on a number of non-standard command line utilities, such as `curl`.
For the alternative solution, we can either execute command line utilities as subprocesses or we can use libraries. Both would amount to reuse, which is good. But the former seems simpler and, within the framework of a robust language, would be sufficiently robust and have acceptable efficiency as well.

**Comment by andmor-** [comment]
Shell scripting has some advantages:
- it is widely known which addresses point 4 across different developers. Almost every developer can do some shell script and not so much for Go or Rust.
- it is available in virtually every POSIX system which addresses points 1 and 2.
- tools like curl, despite sometimes not available out-of-the-box are always available via the package distribution systems.

This makes shell scripts the most standard of the technologies mentioned above and for an organization like CLARIN, standard is generally good.

The current script has also been maintained since then without major issues.

Closing.
