### ISSUE TITLE
Separate functionality better: split off SAML metadata QA validator parts

### ISSUE THREAD

**Issue by sanmai-NL** [clarin-eric/pyFF_config#3]
As this project will now be used within a virtualized deployment, e.g. as a Docker container, it is possible and useful to split out the project in separate components. For one, this will lead to a much smaller and more secure container image.

The main component to be cut out for me is the [SAML metadata QA validator](https://github.com/clarin-eric/SAML_metadata_QA_validator). This requires Java and Ant, so it is big, and is not critical to the AAI infrastructure of the SPF (though very useful). The reason it was included in `control.sh` in the first place is because it relies on the state (stage) of SAML metadata processing and inclusion was the easiest way of coupling.

**Comment by andmor-** [comment]
The [SAML metadata QA validator](https://github.com/clarin-eric/SAML_metadata_QA_validator) was removed and is now only used by the CI system of [the SPs metadata repository](https://github.com/clarin-eric/SPF-SPs-metadata) to automatically generate the [QA assessment report](https://clarin-eric.github.io/SPF-SPs-metadata/page/master_qa_report.html). This is now the right place to run it since this is the entry point of new metadata.

This allowed Java and Ant to be removed from Docker image running pyFF. The current image is 180MB which seems OK but there is room for improvement if this becomes an issue.
